export const APP_INFO = {
  name: 'Mind Miracles',
  tagline: 'Transforming lives through professional psychology services',
  phone: '+91-779-808-2219',
  email: 'mindmiracles1707@gmail.com',
  address: 'Pune, Maharashtra, India',
  founded: 2019,
  founder: 'Ms. Sonali Khade',
  founderTitle: 'Psychologist and Hypnotherapist',
  socialLinks: {
    linkedin: 'https://linkedin.com/in/ms-sonali-khade-79b674331',
    facebook: 'https://facebook.com/share/1DZRPYsPws',
    instagram: 'https://instagram.com/mind_miracles_',
    youtube: 'https://youtube.com/@ms.sonaleepsychologist',
    whatsapp: 'https://api.whatsapp.com/send/?phone=917798082219',
  },
};

export const COURSE_CATEGORIES = [
  {
    id: 'hypnotherapy',
    title: 'Hypnotherapy',
    description: 'Deep healing through guided hypnosis',
    icon: 'brain',
    color: '#1e3a5f',
  },
  {
    id: 'counseling',
    title: 'Psychological Counseling',
    description: 'Professional mental health support',
    icon: 'heart',
    color: '#3b82f6',
  },
  {
    id: 'workshops',
    title: 'Workshops',
    description: 'Interactive group sessions',
    icon: 'users',
    color: '#14B8A6',
  },
  {
    id: 'mind-power',
    title: 'Mind Power',
    description: 'Unlock your mental potential',
    icon: 'zap',
    color: '#f59e0b',
  },
];

export const COURSES = [
  {
    id: '1',
    title: 'Anxiety Management',
    category: 'counseling',
    description: 'Learn effective techniques to manage and overcome anxiety through cognitive behavioral therapy and mindfulness practices.',
    duration: '8 weeks',
    sessions: 8,
    level: 'Beginner',
    price: 5000,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    features: ['Weekly one-on-one sessions', 'Personalized coping strategies', 'Progress tracking', '24/7 support access'],
    curriculum: [
      'Understanding anxiety and its triggers',
      'Breathing and relaxation techniques',
      'Cognitive restructuring',
      'Exposure therapy basics',
      'Building resilience',
      'Maintaining progress',
    ],
  },
  {
    id: '2',
    title: 'Self-Hypnosis Mastery',
    category: 'hypnotherapy',
    description: 'Master the art of self-hypnosis to access your subconscious mind and create positive changes in your life.',
    duration: '6 weeks',
    sessions: 6,
    level: 'Intermediate',
    price: 7000,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    features: ['Guided hypnosis recordings', 'Interactive workshops', 'Self-practice exercises', 'Certification on completion'],
    curriculum: [
      'Introduction to hypnosis',
      'Deepening techniques',
      'Creating positive suggestions',
      'Anchoring techniques',
      'Advanced self-hypnosis',
      'Integration and practice',
    ],
  },
  {
    id: '3',
    title: 'Youth Mental Wellness',
    category: 'workshops',
    description: 'Specially designed for young adults to navigate challenges of modern life, build confidence, and develop emotional intelligence.',
    duration: '4 weeks',
    sessions: 4,
    level: 'All Levels',
    price: 3500,
    image: 'https://images.unsplash.com/photo-1523246005618-996d50ba47f1?w=800',
    features: ['Group sessions', 'Peer support network', 'Practical life skills', 'Stress management tools'],
    curriculum: [
      'Understanding emotions',
      'Building self-esteem',
      'Effective communication',
      'Goal setting and achievement',
    ],
  },
  {
    id: '4',
    title: 'Stress & Burnout Recovery',
    category: 'counseling',
    description: 'Comprehensive program to recover from chronic stress and burnout, restoring balance and vitality.',
    duration: '10 weeks',
    sessions: 10,
    level: 'Intermediate',
    price: 8500,
    image: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800',
    features: ['Comprehensive assessment', 'Personalized recovery plan', 'Lifestyle modifications', 'Follow-up support'],
    curriculum: [
      'Stress assessment and awareness',
      'Identifying burnout patterns',
      'Boundary setting',
      'Restoration techniques',
      'Sustainable lifestyle changes',
      'Building support systems',
    ],
  },
  {
    id: '5',
    title: 'Confidence Building',
    category: 'mind-power',
    description: 'Transform your self-image and build unshakeable confidence through proven psychological techniques.',
    duration: '5 weeks',
    sessions: 5,
    level: 'Beginner',
    price: 4500,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
    features: ['Personalized coaching', 'Practical exercises', 'Video recordings', 'Ongoing support'],
    curriculum: [
      'Identifying limiting beliefs',
      'Reframing self-perception',
      'Body language techniques',
      'Public speaking skills',
      'Maintaining confidence',
    ],
  },
  {
    id: '6',
    title: 'Sleep Therapy',
    category: 'hypnotherapy',
    description: 'Overcome insomnia and sleep disorders through relaxation techniques and hypnotherapy.',
    duration: '4 weeks',
    sessions: 4,
    level: 'All Levels',
    price: 4000,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800',
    features: ['Sleep assessment', 'Customized sleep plan', 'Hypnotherapy sessions', 'Sleep hygiene education'],
    curriculum: [
      'Understanding sleep disorders',
      'Relaxation techniques',
      'Sleep hypnosis scripts',
      'Sleep hygiene practices',
    ],
  },
];

export const EXPERTS = [
  {
    id: '1',
    name: 'Ms. Sonali Khade',
    title: 'Founder & Principal Psychologist',
    specialization: ['Anxiety', 'Depression', 'Hypnotherapy', 'Youth Counseling'],
    experience: '5+ years',
    education: 'Masters in Psychology',
    image: require('../assets/mm_images/sonali_image.png'),
    rating: 4.9,
    reviews: 150,
    available: true,
    consultationTypes: ['Video Call', 'Voice Call', 'Chat', 'In-Person'],
  },
];

export const MENTAL_HEALTH_TESTS = [
  {
    id: 'anxiety',
    title: 'Anxiety Assessment',
    description: 'Evaluate your anxiety levels using the GAD-7 standardized questionnaire',
    questions: 7,
    duration: '5 min',
    icon: 'alert-circle',
    color: '#F59E0B',
    testQuestions: [
      { id: 1, question: 'Feeling nervous, anxious, or on edge?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 2, question: 'Not being able to stop or control worrying?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 3, question: 'Worrying too much about different things?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 4, question: 'Trouble relaxing?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 5, question: 'Being so restless that it is hard to sit still?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 6, question: 'Becoming easily annoyed or irritable?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 7, question: 'Feeling afraid as if something awful might happen?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
    ],
  },
  {
    id: 'depression',
    title: 'Depression Screening',
    description: 'Screen for depression symptoms using the PHQ-9 questionnaire',
    questions: 9,
    duration: '7 min',
    icon: 'cloud-rain',
    color: '#6366F1',
    testQuestions: [
      { id: 1, question: 'Little interest or pleasure in doing things?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 2, question: 'Feeling down, depressed, or hopeless?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 3, question: 'Trouble falling or staying asleep, or sleeping too much?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 4, question: 'Feeling tired or having little energy?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 5, question: 'Poor appetite or overeating?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 6, question: 'Feeling bad about yourself or that you are a failure?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 7, question: 'Trouble concentrating on things?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 8, question: 'Moving or speaking slowly or being fidgety?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
      { id: 9, question: 'Thoughts of being better off dead or hurting yourself?', options: ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'] },
    ],
  },
  {
    id: 'stress',
    title: 'Stress Level Check',
    description: 'Measure your current stress levels and identify stressors',
    questions: 10,
    duration: '5 min',
    icon: 'activity',
    color: '#EF4444',
    testQuestions: [
      { id: 1, question: 'How often do you feel overwhelmed by your responsibilities?', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'] },
      { id: 2, question: 'Do you have trouble sleeping due to stress?', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'] },
      { id: 3, question: 'How often do you feel rushed or pressed for time?', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'] },
      { id: 4, question: 'Do you experience physical symptoms like headaches due to stress?', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'] },
      { id: 5, question: 'How often do you feel irritable or short-tempered?', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'] },
      { id: 6, question: 'Do you find it hard to concentrate on tasks?', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'] },
      { id: 7, question: 'How often do you feel anxious about upcoming events?', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'] },
      { id: 8, question: 'Do you neglect self-care due to being busy?', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'] },
      { id: 9, question: 'How often do you feel disconnected from others?', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'] },
      { id: 10, question: 'Do you feel like you have lost control over your life?', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'] },
    ],
  },
  {
    id: 'wellness',
    title: 'Overall Wellness',
    description: 'Comprehensive assessment of your mental, emotional, and physical wellness',
    questions: 15,
    duration: '10 min',
    icon: 'heart',
    color: '#22C55E',
    testQuestions: [
      { id: 1, question: 'How would you rate your overall mental health?', options: ['Excellent', 'Good', 'Fair', 'Poor', 'Very Poor'] },
      { id: 2, question: 'How often do you engage in physical activity?', options: ['Daily', '3-4 times a week', '1-2 times a week', 'Rarely', 'Never'] },
      { id: 3, question: 'How many hours of sleep do you get on average?', options: ['8+ hours', '6-7 hours', '5-6 hours', '4-5 hours', 'Less than 4 hours'] },
      { id: 4, question: 'How often do you practice mindfulness or meditation?', options: ['Daily', '3-4 times a week', '1-2 times a week', 'Rarely', 'Never'] },
      { id: 5, question: 'How satisfied are you with your relationships?', options: ['Very satisfied', 'Satisfied', 'Neutral', 'Dissatisfied', 'Very dissatisfied'] },
      { id: 6, question: 'How often do you feel lonely or isolated?', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'] },
      { id: 7, question: 'How well do you manage your work-life balance?', options: ['Very well', 'Well', 'Adequately', 'Poorly', 'Very poorly'] },
      { id: 8, question: 'How often do you eat a balanced, healthy diet?', options: ['Always', 'Often', 'Sometimes', 'Rarely', 'Never'] },
      { id: 9, question: 'How would you rate your self-esteem?', options: ['Very high', 'High', 'Average', 'Low', 'Very low'] },
      { id: 10, question: 'How often do you set and achieve personal goals?', options: ['Always', 'Often', 'Sometimes', 'Rarely', 'Never'] },
      { id: 11, question: 'How often do you seek help when facing challenges?', options: ['Always', 'Often', 'Sometimes', 'Rarely', 'Never'] },
      { id: 12, question: 'How would you rate your ability to handle emotions?', options: ['Excellent', 'Good', 'Average', 'Poor', 'Very poor'] },
      { id: 13, question: 'How often do you engage in hobbies or activities you enjoy?', options: ['Daily', 'Weekly', 'Monthly', 'Rarely', 'Never'] },
      { id: 14, question: 'How connected do you feel to your community?', options: ['Very connected', 'Connected', 'Neutral', 'Disconnected', 'Very disconnected'] },
      { id: 15, question: 'How optimistic are you about your future?', options: ['Very optimistic', 'Optimistic', 'Neutral', 'Pessimistic', 'Very pessimistic'] },
    ],
  },
];

export const DAILY_AFFIRMATIONS = [
  { text: 'I am worthy of love and happiness', author: 'Mind Miracles' },
  { text: 'Every day, in every way, I am getting better and better', author: 'Émile Coué' },
  { text: 'My potential is limitless, and I choose to unlock it today', author: 'Mind Miracles' },
  { text: 'I release all negative thoughts and embrace positivity', author: 'Mind Miracles' },
  { text: 'I am stronger than my challenges', author: 'Mind Miracles' },
  { text: 'Peace flows through me like a gentle river', author: 'Mind Miracles' },
  { text: 'I trust the journey of my life', author: 'Mind Miracles' },
  { text: 'I deserve success and abundance', author: 'Mind Miracles' },
];

export const HELPLINE_NUMBERS = [
  { name: 'iCall', phone: '9152987821', available: 'Mon-Sat, 8am-10pm' },
  { name: 'Vandrevala Foundation', phone: '1860-2662-345', available: '24/7' },
  { name: 'NIMHANS Helpline', phone: '+91-80-4611-0007', available: '24/7' },
];

export const TIME_SLOTS = [
  '09:00 AM', '10:00 AM', '11:00 AM', '12:00 PM',
  '02:00 PM', '03:00 PM', '04:00 PM', '05:00 PM', '06:00 PM',
];

export const BOOKING_REASONS = [
  'First Consultation',
  'Follow-up Session',
  'Course Related Query',
  'Mental Health Assessment',
  'Career Guidance',
  'Relationship Issues',
  'Stress Management',
  'Other',
];
